# Generated by Django 5.2.4 on 2025-07-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ned_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='csl_data',
            field=models.JSONField(
                blank=True,
                help_text='Reference data in CSL-JSON format.',
                null=True,
                verbose_name='csl data',
            ),
        ),
    ]
