# Generated by Django 5.2.4 on 2025-07-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ned_app', '0003_populate_csl_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='citation',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='doi',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='publication_type',
        ),
        migrations.AddField(
            model_name='reference',
            name='title',
            field=models.CharField(default='', editable=False, help_text='The title of paper or manuscript.', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='author',
            field=models.CharField(editable=False, help_text='The name(s) of the author(s).', max_length=255, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='year',
            field=models.IntegerField(editable=False, help_text='The year the study was published.', verbose_name='year'),
        ),
    ]
