# Generated by Django 5.2.5 on 2025-08-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ned_app', '0007_remove_component_nistir_subelement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nistirgroupelement',
            name='major_group_element',
        ),
        migrations.RemoveField(
            model_name='nistirindivelement',
            name='group_element',
        ),
        migrations.RemoveField(
            model_name='nistirsubelement',
            name='indiv_element',
        ),
        migrations.DeleteModel(
            name='NistirMajorGroupElement',
        ),
        migrations.DeleteModel(
            name='NistirGroupElement',
        ),
        migrations.DeleteModel(
            name='NistirIndivElement',
        ),
        migrations.DeleteModel(
            name='NistirSubElement',
        ),
    ]
