# Generated by Django 5.2.5 on 2025-09-03 02:56

import ned_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ned_app', '0008_remove_nistirgroupelement_major_group_element_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='component_id',
            field=models.CharField(
                blank=True,
                help_text='Component ID including NISTIR identifiers (e.g., A.10.1.1).',
                max_length=20,
                null=True,
                unique=True,
                validators=[ned_app.validators.validate_nistir_component_id],
                verbose_name='component id',
            ),
        ),
        migrations.AddField(
            model_name='component',
            name='element',
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text='NISTIR element ID and description.',
                max_length=255,
                null=True,
                verbose_name='element',
            ),
        ),
        migrations.AddField(
            model_name='component',
            name='group',
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text='NISTIR group ID and description.',
                max_length=255,
                null=True,
                verbose_name='group',
            ),
        ),
        migrations.AddField(
            model_name='component',
            name='major_group',
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text='NISTIR major group ID and description.',
                max_length=255,
                null=True,
                verbose_name='major group',
            ),
        ),
        migrations.AddField(
            model_name='component',
            name='subelement',
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text='NISTIR subelement ID and description.',
                max_length=255,
                null=True,
                verbose_name='subelement',
            ),
        ),
    ]
