# Generated by Django 5.2.5 on 2025-09-03 17:40

from django.db import migrations


def copy_component_links(apps, schema_editor):
    """
    Copy component links from the existing component field to the new component_new field.
    """
    # Get the historical models
    Experiment = apps.get_model('ned_app', 'Experiment')
    FragilityModel = apps.get_model('ned_app', 'FragilityModel')

    # Iterate through all Experiment objects
    for experiment in Experiment.objects.all():
        experiment.component_new = experiment.component
        experiment.save()

    # Iterate through all FragilityModel objects
    for fragility_model in FragilityModel.objects.all():
        fragility_model.component_new = fragility_model.component
        fragility_model.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ned_app', '0011_experiment_component_new_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_component_links),
    ]
