# Generated by Django 5.2.5 on 2026-01-13 22:46

import django.db.models.deletion
import ned_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ned_app', '0013_remove_experiment_component_new_and_more'),
    ]

    operations = [
        # Validator Path Update:
        # Django detected a change in how the validator is referenced (imported vs inline).
        migrations.AlterField(
            model_name='component',
            name='component_id',
            field=models.CharField(
                blank=True,
                help_text='Component ID including NISTIR identifiers (e.g., A.10.1.1).',
                max_length=20,
                null=True,
                unique=True,
                validators=[ned_app.validators.validate_nistir_component_id],
                verbose_name='component id',
            ),
        ),
        # Validator Path Update:
        # Django detected a change in how the validator is referenced (imported vs inline).
        migrations.AlterField(
            model_name='component',
            name='id',
            field=models.CharField(
                max_length=10,
                primary_key=True,
                serialize=False,
                validators=[ned_app.validators.validate_nistir_component_id],
                verbose_name='id',
            ),
        ),
        # Typo Fix:
        # Corrected typo in help_text.
        migrations.AlterField(
            model_name='experiment',
            name='comp_description',
            field=models.TextField(
                help_text='General description of the type of component.',
                verbose_name='component description',
            ),
        ),
        # Typo Fix:
        # Corrected typo in help_text.
        migrations.AlterField(
            model_name='experiment',
            name='comp_detail',
            field=models.CharField(
                blank=True,
                help_text='Classification or short description of the component attachment detailing.',
                max_length=100,
                verbose_name='component detail tag',
            ),
        ),
        # Schema Drift Fix:
        # Enforcing `null=False` (NOT NULL) to match models.py.
        # This field was temporarily nullable during the component refactor (migrations 0011-0013).
        migrations.AlterField(
            model_name='experiment',
            name='component',
            field=models.ForeignKey(
                help_text='Identifier of the component type',
                on_delete=django.db.models.deletion.PROTECT,
                to='ned_app.component',
                to_field='component_id',
            ),
        ),
        # Typo Fix:
        # Corrected typo in help_text.
        migrations.AlterField(
            model_name='experiment',
            name='design_objective',
            field=models.TextField(
                blank=True,
                help_text='General description of the performance level to which the specimen was designed, e.g., code compliant, common construction practice, low-damage-design, or meeting a certain damage objective under a specific loading condition.',
                verbose_name='design objective',
            ),
        ),
        # Typo Fix:
        # Corrected typo in help_text.
        migrations.AlterField(
            model_name='experiment',
            name='prior_damage_repaired',
            field=models.TextField(
                blank=True,
                help_text='TRUE if prior damage was noted and repaired prior to this test. FALSE if prior damage was noted and not repaired. Or, a general description of the previous damage that was repaired.',
                max_length=255,
                verbose_name='is prior damage repaired',
            ),
        ),
        # Typo Fix:
        # Corrected typo in help_text.
        migrations.AlterField(
            model_name='experiment',
            name='reviewer',
            field=models.CharField(
                blank=True,
                help_text='Individual or institution responsible for documenting this particular fragility in the database.',
                max_length=50,
                verbose_name='reviewer',
            ),
        ),
        # Typo Fix:
        # Corrected typo in help_text.
        migrations.AlterField(
            model_name='experiment',
            name='size_class',
            field=models.CharField(
                blank=True,
                help_text='Classification or short description of the general size of this particular components compared to others of the same type (if applicable).',
                max_length=100,
                verbose_name='size classification tag',
            ),
        ),
        # Typo Fix:
        # Corrected typo in help_text.
        migrations.AlterField(
            model_name='fragilitycurve',
            name='basis',
            field=models.CharField(
                blank=True,
                choices=[
                    ('Experiment', 'Experiment'),
                    ('Historical Event', 'Recon'),
                    ('Analytical Study', 'Analytical'),
                    ('Lit Review', 'Lit Review'),
                    ('Other', 'Other'),
                ],
                help_text='Observational basis of the underlying data comprising the fragility curve.',
                max_length=50,
                verbose_name='basis',
            ),
        ),
        # Typo Fix:
        # Corrected typo in help_text.
        migrations.AlterField(
            model_name='fragilitycurve',
            name='reviewer',
            field=models.CharField(
                blank=True,
                help_text='Person or party responsible for uploading this fragility curve to the database.',
                max_length=255,
                verbose_name='reviewer',
            ),
        ),
        # Typo Fix:
        # Corrected typo in help_text.
        migrations.AlterField(
            model_name='fragilitymodel',
            name='comp_description',
            field=models.TextField(
                help_text='General description of the type of component.',
                verbose_name='component description',
            ),
        ),
        # Typo Fix:
        # Corrected typo in help_text.
        migrations.AlterField(
            model_name='fragilitymodel',
            name='comp_detail',
            field=models.CharField(
                blank=True,
                help_text='Classification or short description of the component attachment detailing.',
                max_length=100,
                verbose_name='component detail tag',
            ),
        ),
        # Schema Drift Fix:
        # Enforcing `null=False` (NOT NULL) to match models.py.
        # This field was temporarily nullable during the component refactor (migrations 0011-0013).
        migrations.AlterField(
            model_name='fragilitymodel',
            name='component',
            field=models.ForeignKey(
                help_text='Identifier of the component type.',
                on_delete=django.db.models.deletion.PROTECT,
                to='ned_app.component',
                to_field='component_id',
            ),
        ),
        # Typo Fix:
        # Corrected typo in help_text.
        migrations.AlterField(
            model_name='fragilitymodel',
            name='size_class',
            field=models.CharField(
                blank=True,
                help_text='Classification or short description of the general size of this particular components compared to others of the same type (if applicable).',
                max_length=100,
                verbose_name='size classification tag',
            ),
        ),
    ]
