# Generated by Django 5.2.5 on 2026-04-07 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ned_app', '0024_swap_fragilitymodel_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragilitycurve',
            name='reference',
            field=models.ForeignKey(
                help_text='ID of the published reference documenting.',
                on_delete=django.db.models.deletion.PROTECT,
                to='ned_app.reference',
                to_field='reference_id',
            ),
        ),
    ]
