# Generated by Django 5.2.5 on 2026-06-23 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ned_app', '0029_alter_fragilitymodel_edp_metric'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fragilitymodel',
            name='unique_ref_model',
        ),
        migrations.RemoveConstraint(
            model_name='fragilitymodel',
            name='unique_legacy_model',
        ),
        migrations.RemoveConstraint(
            model_name='fragilitymodel',
            name='non_legacy_requires_edp_metric',
        ),
        migrations.RemoveConstraint(
            model_name='fragilitymodel',
            name='non_legacy_requires_edp_unit',
        ),
        migrations.AlterField(
            model_name='fragilitymodel',
            name='reference',
            field=models.ForeignKey(
                help_text='Identifier of a Reference documenting this fragility model.',
                on_delete=django.db.models.deletion.PROTECT,
                to='ned_app.reference',
                to_field='reference_id',
            ),
        ),
        migrations.AddConstraint(
            model_name='fragilitymodel',
            constraint=models.UniqueConstraint(
                fields=('reference', 'model_id'), name='unique_ref_model'
            ),
        ),
        migrations.AddConstraint(
            model_name='fragilitymodel',
            constraint=models.CheckConstraint(
                condition=models.Q(('edp_metric', ''), _negated=True),
                name='requires_edp_metric',
            ),
        ),
        migrations.AddConstraint(
            model_name='fragilitymodel',
            constraint=models.CheckConstraint(
                condition=models.Q(('edp_unit', ''), _negated=True),
                name='requires_edp_unit',
            ),
        ),
    ]
