# Generated by Django 5.2.5 on 2026-07-07 00:41

import django.core.validators
import ned_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ned_app', '0031_alter_experiment_alt_edp_metric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fragilitycurve',
            name='beta',
            field=models.DecimalField(
                decimal_places=3,
                help_text='Lognormal dispersion.',
                max_digits=4,
                null=True,
                validators=[ned_app.validators.validate_positive],
                verbose_name='beta',
            ),
        ),
        migrations.AlterField(
            model_name='fragilitycurve',
            name='median',
            field=models.DecimalField(
                decimal_places=4,
                help_text='Median point of the fragility curve.',
                max_digits=9,
                null=True,
                validators=[ned_app.validators.validate_positive],
                verbose_name='median',
            ),
        ),
        migrations.AlterField(
            model_name='fragilitycurve',
            name='probability',
            field=models.DecimalField(
                decimal_places=2,
                help_text='Mutually exclusive probability of this damage state.',
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
                verbose_name='probability',
            ),
        ),
    ]
