# Generated by Django 5.2.5 on 2026-07-08 17:04

import ned_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ned_app', '0033_require_fragilitymodel_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='reference_label',
            field=models.CharField(
                blank=True,
                help_text='Optional label used in place of the first-author surname when building the reference id (e.g. "FEMA_P58" -> FEMA_P58-<year>).',
                max_length=100,
                validators=[ned_app.validators.validate_reference_label],
                verbose_name='reference label',
            ),
        ),
    ]
