# Generated by Django 5.2.15 on 2026-09-18 17:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ned_app', '0035_alter_experiment_edp_metric_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='pdf_saved',
        ),
    ]
