
[tool.codespell]
ignore-words = "ignore_words.txt"
skip = [
    "*/ned_app/*",
    "*/ned_proj/*",
    "*/resources/*",
    "*/visualization_tools/*",
    "*/venv/*",
    'fair-software.md'
]
check-filenames = true
check-hidden = false
count = true
quiet-level = 2

[tool.ruff]
line-length = 85
preview = true
exclude = [
    "*.ipynb",
    "resources/",
    "visualization_tools/",
]

[tool.ruff.lint]
ignore = [
    "D211",
    "D212",
    "Q000",
    "Q003",
    "COM812",
    "D203",
    "ISC001",
    "E501",
    "ERA001",
    "PGH003",
    "FIX002",
    "TD003",
    "S101",
    "N801",
    "S311",
    "G004",
    "SIM102",
    "SIM108",
    "NPY002",
    "F401",
    "TRY003",
]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pylint]
max-args = 15
max-locals = 50
max-returns = 11
max-branches = 50
max-statements = 150
max-bool-expr = 5
