# .github/workflows/ci.yml
name: NED CI/CD

on:
  push:
  pull_request:

jobs:
  # ----- STAGE 1: PARALLEL STATIC CHECKS -----
  lint:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          version: 0.12.9

  format_check:
    name: Ruff Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          args: 'format --check --diff --verbose'
          version: 0.12.9
          
  spell_check:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@v2

  # ----- STAGE 2: TESTING -----
  test:
    name: Run Tests
    needs: [lint, format_check, spell_check]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt
      - name: Run tests
        run: python manage.py test ned_app.tests